### ISSUE TITLE
小程序真机测试

### ISSUE THREAD

**Issue by bestony** [natee/wxapp-2048#1]
Hi,我为您的小程序进行了真机测试。
具体您可以看这个[微信文章](http://mp.weixin.qq.com/s?__biz=MzA5NTQ4NjkyMQ==&mid=2650723004&idx=1&sn=a6bcbf354beca3e745c47e542e119e5c&chksm=88b4e41abfc36d0c547698b6f4f3669b1aa351a879332c2848ffd6618dbf23cb41316dca570a&scene=0#wechat_redirect)
视频源码已经上传至[WeApp-Demo](https://github.com/bestony/WeApp-Demo)

**Comment by bestony** [comment]
https://github.com/natee/wxapp-2048/blob/master/app.json#L22 
这里的iconPath 如果为空会导致无法预览（真机）如果设置为空，就直接删除。或者补上相关内容。

**Comment by natee** [comment]
@bestony 已删除空的icon path

**Comment by bestony** [comment]
后续有需要测试的可以联系我哦~
